### ISSUE TITLE
Not able to route the traffic from ggr router to external services Saucelabs 

### ISSUE THREAD

**Issue by praveenyarabothu** [aerokube/ggr#286] opened 2019-09-03 22:06 UTC
Below is the xml configuration i defined in the ggr quota/test.xml file . I am not able to route the traffic from ggr router to external services like Sauce labs even though config has been defined in quota file . I am able to successfully run the tests on selenoid framework . Need help in solving the traffic to route to sauce labs 

```
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="firefox" defaultVersion="45.0">
    <version number="45.0">
        <region name="1">
            <host name="ondemand.saucelabs.com" port="443" count="1" username="****" password="****" scheme="https" />
        </region>
    </version>
</browser>
<browser name="firefox" defaultVersion="50.0">
    <version number="50.0">
        <region name="1">
            <host name="**************" port="4444" count="1"/>
        </region>
    </version>
    <version number="57.0">
        <region name="1">
            <host name="************" port="4444" count="1"/>
        </region>
    </version>
</browser>
<browser name="chrome" defaultVersion="48.0">
    <version number="48.0">
        <region name="1">
            <host name="********" port="4444" count="1"/>
        </region>
    </version>
</browser>
</qa:browsers>
```

**Comment by vania-pooh** [comment] 2019-09-04 07:15
@praveenyarabothu proxying to HTTPS does not work: https://github.com/aerokube/ggr/issues/273 Try to use HTTP instead (SauceLabs should support it).

**Comment by vania-pooh** [comment] 2019-10-12 16:09
Duplicate of #273.

**Closed by vania-pooh** 2019-10-12 16:09 UTC
Labels: bug
