### ISSUE TITLE
Selenium Alpha 4 returns 401 with GGR

### ISSUE THREAD

**Issue by jsa34** [aerokube/ggr#301] opened 2020-02-06 08:09 UTC
When updating selenium version in project to selenium v.4.0.0-alpha-4, all tests return back a 401 from GGR:
org.openqa.selenium.WebDriverException: 
Unable to parse remote response: 401 Unauthorized

Caused by: org.openqa.selenium.json.JsonException: 
Expected to read a START_MAP but instead have: NUMBER. Last 0 characters read: 

Upon changing selenium version to 4.0.0-alpha-3, the 401 disappears and tests run successfully.  I'm guessing its some change in the test ids/requests that are being sent with the latest alpha release?

**Comment by vania-pooh** [comment] 2020-02-06 11:25
@jsa34 401 could be returned only when incorrect username \ password is specified. This could be caused by incorrect processing of URLs with usernames \ passwords.

**Comment by jsa34** [comment] 2020-02-06 11:51
This is what I assumed, but the only difference I made was updating the selenium libraries to alpha-4 and the requests are unsuccessful...  The username and password in the URL request sent to GGR are identical and the only change was to update selenium version from alpha-3 to alpha-4, so I guess it's selenium's processing of the URL that has changed behaviour?

**Comment by vania-pooh** [comment] 2020-02-06 12:23
@jsa34 yes, could you check whether `Authorization` header is being sent with a new Selenium release?

**Comment by jsa34** [comment] 2020-02-06 15:21
Aha - getting a bit further... They have changed their default HTTP client to netty instead of okhttp.  If I override the prop webdriver.http.factory=okhttp, all is fine.  If I let it go to default or specify netty, it fails... Something about netty!

**Comment by jsa34** [comment] 2020-02-06 15:36
Unless I am missing it somewhere, the netty implementation doesn't appear to send the authorization header...

Okhttp sets it here: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/http/okhttp/CreateOkClient.java (line 58)

But I can't see it set anywhere in netty:
https://github.com/SeleniumHQ/selenium/tree/master/java/client/src/org/openqa/selenium/remote/http/netty

**Comment by vania-pooh** [comment] 2020-02-06 17:35
@jsa34 just tested with Selenium Java 4.0.0-alpha-4 and it works.

**Comment by jsa34** [comment] 2020-02-07 10:27
That's interesting - I can't see how with netty as I can't see the Authorization header set, and unless I explicitly set the prop webdriver.http.factory=okhttp it fails to authenticate... 🤔

**Comment by vania-pooh** [comment] 2020-08-15 09:46
This was fixed on Selenium side.

**Closed by vania-pooh** 2020-08-15 09:46 UTC
