### ISSUE TITLE
cannot create session internet explorer-11 on any hosts after 10 attempt(s)

### ISSUE THREAD

**Issue by benzman81** [aerokube/ggr#116] opened 2017-09-09 18:35 UTC
Now, after an attempt per host works with fix of #114 I still get the below message pretty often.

```
cannot create session internet explorer-11 on any hosts after 10 attempt(s) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 562 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'outBuildHost', ip: 'outBuildHostIp', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-111-generic', java.version: '1.8.0_101'
Driver info: driver.version: RemoteWebDriver
```

Because of the error above we are doing multiple retries of "new RemoteWebDriver" ourself, but I think there must be something wrong. We are running ggr on a linux machine that also starts 10 virtualboxes  of windows using vagrant. Inside of them we start one selenoid per machine. Portforwarding so selenoid is correct.

Any clue what we are doing wrong? We want are running 10 tests in parallel for now.

This is our ggr quota:
```
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="internet explorer" defaultVersion="11">
    <version number="11">
        <region name="1">
            <host name="ourgridhostname" port="4450" count="1"/>
            <host name="ourgridhostname" port="4451" count="1"/>
            <host name="ourgridhostname" port="4452" count="1"/>
            <host name="ourgridhostname" port="4453" count="1"/>
            <host name="ourgridhostname" port="4454" count="1"/>
            <host name="ourgridhostname" port="4455" count="1"/>
            <host name="ourgridhostname" port="4456" count="1"/>
            <host name="ourgridhostname" port="4457" count="1"/>
            <host name="ourgridhostname" port="4458" count="1"/>
            <host name="ourgridhostname" port="4459" count="1"/>
        </region>
    </version>
</browser>
</qa:browsers>
```
We are starting ggr like this:

`nohup ./ggr_linux_amd64 -timeout 120s -users users.htpasswd > ggr.log 2>&1 &`

Starting selenoid on each windows is done with:

`selenoid_windows_386.exe -conf browsers.json -disable-docker -disable-queue -enable-file-upload -timeout 1200s -limit 1 > selenoid.log`

using browser.conf:

```
{
	"internet explorer": {
		"default": "11",
		"versions": {
			"11": {
				"image": [
					"C:\\Users\\IEUser\\Downloads\\IEDriverServer.exe"
				]
			}
		}
	}
}
```

**Comment by vania-pooh** [comment] 2017-09-09 19:30
FYI: `-disable-queue` expects that you manually control your load. If you create more sessions than specified via `-limit` then Selenoid quickly returns an error to Ggr. When you overload one Selenoid - the rest of hosts automatically get more sessions because the first host return an error. Because of that they can be also overloaded. So this works good when overall load is far from 100%. Our distribution is random, so not 100% uniform. E.g. having 100 parallel sessions and 10 hosts with the same weights - one host can get 11 sessions whereas another one - only 9 sessions. This is almost uniform - not absolutely uniform.

**Comment by benzman81** [comment] 2017-09-09 19:45
Well, in our old environment, we had selenium grid running with 10 nodes. This way we could run 10 tests in parallel all the time. What would be a configuration to achieve this with ggr and selenoid?

**Comment by vania-pooh** [comment] 2017-09-09 20:18
Normally we expect you to not turn off the queues. Just try without this flag. In that case Selenoid will behave like Selenium hub does. Did it help?

**Comment by benzman81** [comment] 2017-09-09 21:17
I already tried without disabling the queues, but in that case some nodes didnt pick up any tests at all and tests queued at already busy nodes. This tests was done with a small subset of 25 tetst only, but almost esch run showd this behavior.

**Comment by vania-pooh** [comment] 2017-09-10 06:01
@aandryashin any more suggestions?

**Comment by aandryashin** [comment] 2017-09-10 08:36
Queues work well under high load. I our environment we run hundreds
thousandth  tests against cluster with only 1500 capacity and all tests
done sooner or later. The main goal of ggr was reliability and not
performance. We decided to not implement round robin algorithm to keep ggr
stateless. In our cluster there are multiple ggr instances.

Please try to run tons of tests, in 3-5 times more than your cluster
capacity and see that queues work well.

2017-09-10 9:01 GMT+03:00 Ivan Krutov <notifications@github.com>:

**Comment by benzman81** [comment] 2017-09-10 09:38
@vania-pooh the new ggr version v1.2.7 also fixed the issue that I couldn't work with selenoid queues, at least with my simple test case. I will run out tests with queues enabled the rest of the day to check if this works, too.

@vania-pooh @aandryashin With queues disabled, using above stated configuration, I could reproduce the issue with this simple testcase:

```
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.LocalFileDetector;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class TestMk {

	private static Map<Long, WebDriver> webDrivers = new ConcurrentHashMap<Long, WebDriver>();

	@Test(threadPoolSize = 10, invocationCount = 1000)
	public void test1() throws Exception {
		WebDriver driver = getWebDriver();
		driver.get("http://www.google.com");
		WebElement element = driver.findElement(By.name("q"));
		element.sendKeys("Cheese!");
		element.submit();
		System.out.println("Page title is: " + driver.getTitle());
		// throw new Exception("The test had an error ;-)");
	}

	@BeforeMethod
	public void beforeMethod() throws Exception {
		getWebDriver();
	}

	@AfterMethod
	public void afterMethod() throws Exception {
		long threadId = Thread.currentThread().getId();
		if (webDrivers.containsKey(threadId)) {
			WebDriver webDriver = getWebDriver();
			webDrivers.remove(threadId);
			try {
				webDriver.close();
			}
			catch (Exception e) {
				// ignore
			}
			try {
				webDriver.quit();
			}
			catch (Exception e) {
				// ignore
			}
		}
	}

	private WebDriver getWebDriver() throws MalformedURLException {
		long threadId = Thread.currentThread().getId();
		if (!webDrivers.containsKey(threadId)) {
			URL gridUrl = new URL("http://test:test-password@ourServer:4444/wd/hub");
			DesiredCapabilities desiredCapabilities = DesiredCapabilities.internetExplorer();
			desiredCapabilities.setCapability(InternetExplorerDriver.IE_USE_PER_PROCESS_PROXY, true);
			desiredCapabilities.setCapability(InternetExplorerDriver.IE_SWITCHES, "-private");
			desiredCapabilities.setCapability(InternetExplorerDriver.FORCE_CREATE_PROCESS, true);
			desiredCapabilities.setCapability(InternetExplorerDriver.REQUIRE_WINDOW_FOCUS, false);
			desiredCapabilities.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
			RemoteWebDriver remoteWebDriver = new RemoteWebDriver(gridUrl, desiredCapabilities);
			remoteWebDriver.setFileDetector(new LocalFileDetector());
			webDrivers.put(threadId, remoteWebDriver);
		}
		return webDrivers.get(threadId);
	}

	private void quitDriver() throws Exception {
		long threadId = Thread.currentThread().getId();
		if (webDrivers.containsKey(threadId)) {
			WebDriver webDriver = getWebDriver();
			webDrivers.remove(threadId);
			try {
				webDriver.close();
			}
			catch (Exception e) {
				// ignore
			}
			try {
				webDriver.quit();
			}
			catch (Exception e) {
				// ignore
			}
		}
	}
}

```

After a lot of tests (sometime 160, sometimes 300) all other tests get skipped with the error stated in this issue.

Looking at the machines using vnc right after that, I can see, that some machines have a browser open initializing the driver and some have a browser open in the middle/end of the test. 

I will work with queues now to see if that fully works, but something seems to be wrong with disabled queues. Hopefully you can reproduce it.

**Comment by vania-pooh** [comment] 2017-09-10 11:36
@benzman81 ok. Thank for detailed steps to reproduce the issue. We'll take a look soon.

**Comment by vania-pooh** [comment] 2020-08-15 09:48
This should have been fixed in https://github.com/aerokube/ggr/pull/183.

**Closed by vania-pooh** 2020-08-15 09:48 UTC
